services:
    mailpit:
        image: axllent/mailpit:v1.28
        container_name: mailpit
        volumes:
            - ./mailpit-data:/data
        ports:
            # http
            - "8025:8025"
            # smtp
            - "1025:1025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        healthcheck:
            test: ["CMD", "curl", "--silent", "--fail-with-body", "--max-time", "5", "http://localhost:8025/readyz"]
            interval: 15s
            timeout: 5s
            retries: 2

    postgres:
        image: 'postgis/postgis:18-3.6-alpine'
        environment:
            - 'POSTGRES_DB=mydatabase'
            - 'POSTGRES_PASSWORD=secret'
            - 'POSTGRES_USER=myuser'
        ports:
            - '32779:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
        labels:
            - 'org.springframework.boot.service-connection=postgres'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - shared-net

volumes:
    db-data:

networks:
    shared-net:
        external: true

