package com.b216.umrs.features.movement.model;

public enum PlaceType {
    HOME_RESIDENCE,
    FRIENDS_RELATIVES_HOME,
    WORKPLACE,
    WORK_BUSINESS_TRIP,
    DAYCARE_CENTER,
    SCHOOL,
    COLLEGE_TECHNICAL_SCHOOL,
    UNIVERSITY_INSTITUTE,
    HOSPITAL_CLINIC,
    CULTURAL_INSTITUTION,
    SPORT_FITNESS,
    STORE_MARKET,
    SHOPPING_ENTERTAINMENT_CENTER,
    RESTAURANT_CAFE,
    SUBURB,
    OTHER
}
