name: "Bug Report"
description: "Use for bugs and exceptions"
title: "[Bug] "
labels:
  - "bug"

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Briefly describe the problem
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open ...
        2. Click ...
        3. See ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual result
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Extra info
      description: Logs, screenshots, environment details
    validations:
      required: false