name: General Report
description: Provide general feedback or inquiries
title: "[General] "
labels: ["general"]
assignees: []
body:
  - type: textarea
    id: feedback_or_inquiry
    attributes:
      label: Feedback or Inquiry
      description: Provide your feedback or inquiry.
      placeholder: Share your feedback, question, or concern.
    validations:
      required: true

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other relevant details here.
      placeholder: Context, links, screenshots, or related notes.
    validations:
      required: false
